# Copyright (C) 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/bq/Aquaris5HD/setup-makefiles.sh

# vendor/bq/Aquaris5HD/proprietary/lib/libmtkplayer.so:system/lib/libmtkplayer.so \
# vendor/bq/Aquaris5HD/proprietary/lib/libfmcust.so:system/lib/libfmcust.so \
# vendor/bq/Aquaris5HD/proprietary/lib/libfmjni.so:system/lib/libfmjni.so \
# vendor/bq/Aquaris5HD/proprietary/lib/libfmmt6628.so:system/lib/libfmmt6628.so \
# vendor/bq/Aquaris5HD/proprietary/lib/libaudio.a2dp.default.so:system/lib/libaudio.a2dp.default.so \

PRODUCT_COPY_FILES += \
 vendor/bq/Aquaris5HD/proprietary/etc/agps_profiles_conf.xml:system/etc/agps_profiles_conf.xml \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/mt6628_patch_e2_1_hdr.bin:system/etc/firmware/mt6628_patch_e2_1_hdr.bin \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/WIFI_RAM_CODE_E6:system/etc/firmware/WIFI_RAM_CODE_E6 \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/mt6628/mt6628_fm_v2_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v2_coeff.bin \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/mt6628/mt6628_fm_v4_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v4_coeff.bin \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/mt6628/mt6628_fm_v3_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v3_coeff.bin \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/mt6628/mt6628_fm_v5_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v5_patch.bin \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/mt6628/mt6628_fm_v2_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v2_patch.bin \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/mt6628/mt6628_fm_v4_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v4_patch.bin \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/mt6628/mt6628_fm_v1_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v1_coeff.bin \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/mt6628/mt6628_fm_v3_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v3_patch.bin \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/mt6628/mt6628_fm_rom.bin:system/etc/firmware/mt6628/mt6628_fm_rom.bin \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/mt6628/mt6628_fm_v1_patch.bin:system/etc/firmware/mt6628/mt6628_fm_v1_patch.bin \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/mt6628/mt6628_fm_v5_coeff.bin:system/etc/firmware/mt6628/mt6628_fm_v5_coeff.bin \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/mt6628_ant_m1.cfg:system/etc/firmware/mt6628_ant_m1.cfg \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/mt6628_patch_e2_0_hdr.bin:system/etc/firmware/mt6628_patch_e2_0_hdr.bin \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/mt6628_patch_e1_hdr.bin:system/etc/firmware/mt6628_patch_e1_hdr.bin \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/WIFI_RAM_CODE:system/etc/firmware/WIFI_RAM_CODE \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/S_ANDRO_SFL.ini:system/etc/firmware/S_ANDRO_SFL.ini \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/WIFI_RAM_CODE_MT6628:system/etc/firmware/WIFI_RAM_CODE_MT6628 \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/catcher_filter.bin:system/etc/firmware/catcher_filter.bin \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/WMT.cfg:system/etc/firmware/WMT.cfg \
 vendor/bq/Aquaris5HD/proprietary/etc/firmware/modem.img:system/etc/firmware/modem.img \
 vendor/bq/Aquaris5HD/proprietary/etc/throttle.sh:system/etc/throttle.sh \
 vendor/bq/Aquaris5HD/proprietary/etc/mtk_omx_core.cfg:system/etc/mtk_omx_core.cfg \
 vendor/bq/Aquaris5HD/proprietary/etc/audio_effects.conf:system/etc/audio_effects.conf \
 vendor/bq/Aquaris5HD/proprietary/etc/gps.conf:system/etc/gps.conf \
 vendor/bq/Aquaris5HD/proprietary/bin/drvbd:system/bin/drvbd \
 vendor/bq/Aquaris5HD/proprietary/bin/hald:system/bin/hald \
 vendor/bq/Aquaris5HD/proprietary/bin/6620_launcher:system/bin/6620_launcher \
 vendor/bq/Aquaris5HD/proprietary/bin/akmd8963:system/bin/akmd8963 \
 vendor/bq/Aquaris5HD/proprietary/bin/akmd8975:system/bin/akmd8975 \
 vendor/bq/Aquaris5HD/proprietary/bin/ami304d:system/bin/ami304d \
 vendor/bq/Aquaris5HD/proprietary/bin/bmm050d:system/bin/bmm050d \
 vendor/bq/Aquaris5HD/proprietary/bin/ccci_fsd:system/bin/ccci_fsd \
 vendor/bq/Aquaris5HD/proprietary/bin/ccci_mdinit:system/bin/ccci_mdinit \
 vendor/bq/Aquaris5HD/proprietary/bin/geomagneticd:system/bin/geomagneticd \
 vendor/bq/Aquaris5HD/proprietary/bin/memsicd:system/bin/memsicd \
 vendor/bq/Aquaris5HD/proprietary/bin/msensord:system/bin/msensord \
 vendor/bq/Aquaris5HD/proprietary/bin/mtk_agpsd:system/bin/mtk_agpsd \
 vendor/bq/Aquaris5HD/proprietary/bin/muxreport:system/bin/muxreport \
 vendor/bq/Aquaris5HD/proprietary/bin/nvram_daemon:system/bin/nvram_daemon \
 vendor/bq/Aquaris5HD/proprietary/bin/nvram_agent_binder:system/bin/nvram_agent_binder \
 vendor/bq/Aquaris5HD/proprietary/bin/orientationd:system/bin/orientationd \
 vendor/bq/Aquaris5HD/proprietary/bin/permission_check:system/bin/permission_check \
 vendor/bq/Aquaris5HD/proprietary/bin/pppd:system/bin/pppd \
 vendor/bq/Aquaris5HD/proprietary/bin/pppd_dt:system/bin/pppd_dt \
 vendor/bq/Aquaris5HD/proprietary/bin/rild:system/bin/rild \
 vendor/bq/Aquaris5HD/proprietary/bin/rildmd2:system/bin/rildmd2 \
 vendor/bq/Aquaris5HD/proprietary/bin/stp_dump3:system/bin/stp_dump3 \
 vendor/bq/Aquaris5HD/proprietary/bin/thermal:system/bin/thermal \
 vendor/bq/Aquaris5HD/proprietary/bin/thermal_manager:system/bin/thermal_manager \
 vendor/bq/Aquaris5HD/proprietary/bin/wlan_loader:system/bin/wlan_loader \
 vendor/bq/Aquaris5HD/proprietary/lib/liba3m.so:system/lib/liba3m.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libacdk.so:system/lib/libacdk.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libawb_wrap.so:system/lib/libawb_wrap.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libI420colorconvert.so:system/lib/libI420colorconvert.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libJpgDecPipe.so:system/lib/libJpgDecPipe.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libmhalImageCodec.so:system/lib/libmhalImageCodec.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libmmprofile.so:system/lib/libmmprofile.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libmmprofile_jni.so:system/lib/libmmprofile_jni.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libmp4enc_xa.ca7.so:system/lib/libmp4enc_xa.ca7.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libmpodecoder.so:system/lib/libmpodecoder.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libMtkOmxCore.so:system/lib/libMtkOmxCore.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libMtkOmxVdec.so:system/lib/libMtkOmxVdec.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libMtkOmxVenc.so:system/lib/libMtkOmxVenc.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libsched.so:system/lib/libsched.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libSwJpgCodec.so:system/lib/libSwJpgCodec.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libMtkVideoTranscoder.so:system/lib/libMtkVideoTranscoder.so \
 vendor/bq/Aquaris5HD/proprietary/lib/librsa_hw.so:system/lib/librsa_hw.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libion.so:system/lib/libion.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libblisrc.so:system/lib/libblisrc.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libblisrc32.so:system/lib/libblisrc32.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libdpframework.so:system/lib/libdpframework.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libbluetooth_mtk.so:system/lib/libbluetooth_mtk.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libJpgEncPipe.so:system/lib/libJpgEncPipe.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libaudiodcrflt.so:system/lib/libaudiodcrflt.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libcameracustom.so:system/lib/libcameracustom.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libcustom_prop.so:system/lib/libcustom_prop.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libvcodec_oal.so:system/lib/libvcodec_oal.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libstagefright_memutil.so:system/lib/libstagefright_memutil.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libvcodec_utility.so:system/lib/libvcodec_utility.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libvcodecdrv.so:system/lib/libvcodecdrv.so \
 vendor/bq/Aquaris5HD/proprietary/lib/mtk-ril.so:system/lib/mtk-ril.so \
 vendor/bq/Aquaris5HD/proprietary/lib/mtk-rilmd2.so:system/lib/mtk-rilmd2.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libnvram.so:system/lib/libnvram.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libcam.utils.so:system/lib/libcam.utils.so \
 vendor/bq/Aquaris5HD/proprietary/lib/librilmtk.so:system/lib/librilmtk.so \
 vendor/bq/Aquaris5HD/proprietary/lib/librilmtkmd2.so:system/lib/librilmtkmd2.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libutilrilmtk.so:system/lib/libutilrilmtk.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libmsbc_mtk.so:system/lib/libmsbc_mtk.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libaudiocomponentengine.so:system/lib/libaudiocomponentengine.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libbluetoothdrv.so:system/lib/libbluetoothdrv.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libdpframework_os.so:system/lib/libdpframework_os.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libcustom_nvram.so:system/lib/libcustom_nvram.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libbwc.so:system/lib/libbwc.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libhwm.so:system/lib/libhwm.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libkeystore_client.so:system/lib/libkeystore_client.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libfeatureio.so:system/lib/libfeatureio.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libfmcust.so:system/lib/libfmcust.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libfmjni.so:system/lib/libfmjni.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libfmmt6628.so:system/lib/libfmmt6628.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libmtkplayer.so:system/lib/libmtkplayer.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libmtklimiter.so:system/lib/libmtklimiter.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libbessound_mtk.so:system/lib/libbessound_mtk.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libcam.campipe.so:system/lib/libcam.campipe.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
 vendor/bq/Aquaris5HD/proprietary/lib/lib3a.so:system/lib/lib3a.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libmpo.so:system/lib/libmpo.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libcam.client.so:system/lib/libcam.client.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libssladp.so:system/lib/libssladp.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libmpoencoder.so:system/lib/libmpoencoder.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libaudiocustparam.so:system/lib/libaudiocustparam.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libdpframework_plat.so:system/lib/libdpframework_plat.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libdrmmtkplugin.so:system/lib/libdrmmtkplugin.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libdrmmtkutil.so:system/lib/libdrmmtkutil.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libdrmmtkwhitelist.so:system/lib/libdrmmtkwhitelist.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libcamdrv.so:system/lib/libcamdrv.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libaudiosetting.so:system/lib/libaudiosetting.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libbessound_hd_mtk.so:system/lib/libbessound_hd_mtk.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libimageio.so:system/lib/libimageio.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libmatv_cust.so:system/lib/libmatv_cust.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libmnl.so:system/lib/libmnl.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libmtkshifter.so:system/lib/libmtkshifter.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libaed.so:system/lib/libaed.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libcvsd_mtk.so:system/lib/libcvsd_mtk.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libfile_op.so:system/lib/libfile_op.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libm4u.so:system/lib/libm4u.so \
 vendor/bq/Aquaris5HD/proprietary/lib/hw/hwcomposer.mt6589.so:system/lib/hw/hwcomposer.mt6589.so.back \
 vendor/bq/Aquaris5HD/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
 vendor/bq/Aquaris5HD/proprietary/lib/hw/lights.default.so:system/lib/hw/lights.default.so \
 vendor/bq/Aquaris5HD/proprietary/lib/hw/power.default.so:system/lib/hw/power.default.so \
 vendor/bq/Aquaris5HD/proprietary/lib/hw/local_time.default.so:system/lib/hw/local_time.default.so \
 vendor/bq/Aquaris5HD/proprietary/lib/hw/camera.default.so:system/lib/hw/camera.default.so \
 vendor/bq/Aquaris5HD/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
 vendor/bq/Aquaris5HD/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
 vendor/bq/Aquaris5HD/proprietary/lib/hw/keystore.default.so:system/lib/hw/keystore.default.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libaudiocompensationfilter.so:system/lib/libaudiocompensationfilter.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libcam_camera_exif.so:system/lib/libcam_camera_exif.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libcamalgo.so:system/lib/libcamalgo.so \
 vendor/bq/Aquaris5HD/proprietary/lib/libnvram_daemon_callback.so:system/lib/libnvram_daemon_callback.so \
 vendor/bq/Aquaris5HD/proprietary/xbin/libmnlp_mt6628:system/xbin/libmnlp_mt6628 \
 vendor/bq/Aquaris5HD/proprietary/xbin/mnld:system/xbin/mnld \
 vendor/bq/Aquaris5HD/proprietary/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N/full_model.bin:system/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N/full_model.bin \
 vendor/bq/Aquaris5HD/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2/full_model.bin \
 vendor/bq/Aquaris5HD/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin \
 vendor/bq/Aquaris5HD/proprietary/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin \
 vendor/bq/Aquaris5HD/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24/full_model.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24/full_model.bin \
 vendor/bq/Aquaris5HD/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24/full_model.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24/full_model.bin \
 vendor/bq/Aquaris5HD/proprietary/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24/full_model.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24/full_model.bin \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/egl/libGLESv1_CM_mtk.so:system/vendor/lib/egl/libGLESv1_CM_mtk.so \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/egl/libEGL_mtk.so:system/vendor/lib/egl/libEGL_mtk.so \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/egl/libGLESv2_mtk.so:system/vendor/lib/egl/libGLESv2_mtk.so \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/libBLPP.so:system/vendor/lib/libBLPP.so \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/hw/gralloc.mt6589.so:system/vendor/lib/hw/gralloc.mt6589.so \
 vendor/bq/Aquaris5HD/proprietary/vendor/lib/hw/audio.a2dp.blueangel.so:system/vendor/lib/hw/audio.a2dp.blueangel.so
PRODUCT_COPY_FILES += \
